public class MesesAno {
    public static void main(String[] args){
        String[] Meses = { "Janeiro", "Fevereiro", "Março","Abril","Maio","Junho",
    "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"};

    int[] dias = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

    int = 0;
    do{
        System.out.println("O Mês" + Meses[i] "possui" + dias[i] + "Dias.");
        i++;
    
    }while(i == Meses.length);
    }
    
}
